services:
    animals:
        image: sergiobarriel/emoji-api-animals
        ports:
            - "5000:80"
    foods:
        image: sergiobarriel/emoji-api-foods
        ports:
            - "5001:80"

    sports:
        image: sergiobarriel/emoji-api-sports
        ports:
            - "5002:80"            